ansible_user: centos
ansibullbot_receiver_enabled: true

ansibullbot_github_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64336339633164353330346262343334326164346165313463653535333938626361366564326265
          6430333936663764663335616261373534343664306236360a633833373365306334376363303364
          61383631303035323862666365613639373139626665323131613937363765386534306363363038
          3466613564626639300a323465323739646538613965306564343835663230366339306138626239
          6565

ansibullbot_github_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32316231313930336661323831346432333839396231636633306539316634373766623262646131
          3663326537316530623461393635313336313566613630640a366261373633653466663036653630
          39316230363438333730366139363462633966333439353762326463383764656632313962333464
          3537653462633133620a366333613063636434353365336439363337336633646239363263636238
          63616465666162636366353932633330306437663338643734633665373332363533633836313363
          3031396264646336343233646435626333306433363261346631

ansibullbot_shippable_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323936336635643537373832633937326138306334336461306634306565663561346262636461
          3636373539663831326338666331353831396562363334660a636530383433633736653434383137
          34323365363430613732383332373265653139643738336139323633646131623430623066663930
          6162363537616537300a643732353963363761393134646436336533313039663066323534646665
          36373662666662313034366562656463373431376562663935613563386437356131663138373261
          6161663961333533663062383066363130643161663237363165

ansibullbot_slack_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61346536653630656533633566373230316266313531343931313532313037656330656661386633
          3963323838303634383762326331306538363434326437350a623862653363346163613935656462
          30363438393263306366343538336635386661343764303362616430643736326439623533393961
          3062333061343434350a633662373861666638643037626230393933646637633436353231383838
          65373636373139656264343038383338643265326166613864633663613362303636613432643737
          37663061386162643964316436653437316435613534383132336530353830343532316333663566
          62396231623536633866613236386162383330356465383532323235306532336136633335363631
          65616564386466323139

ansibullbot_slack_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30316336623938336266333130383338336633633963643035376266353537626462386631366563
          3664313665326361363062393831623630323635663931390a386335616464646262373136333033
          62346130353733323835353364356632653362386166303964366633633365396334653836306432
          3532333336353831650a666663353132376239323966303562646632643464313431393836646161
          62653634343664383532373735643962303666333530623065663230336538633637353563623135
          6237343134343037653738636134316239303163326532326135

ansibullbot_sentry_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63323033383535323038326635396566643832393334376239356435353766656531363765323164
          3431313663353637616332613361356534323866363165610a313465316435356465333830663637
          33343336366137666437613031393164336164303462373831383461313437353038626436366230
          3031623739666230380a323530363137333533663164303830373730373162613864656661343561
          39336661386633373538373633336262373939386165643162646137376532656233396433353434
          38336265326137343963363333323434353230626665666663346637333430333064333436343037
          373238326163396130616162616363643832

# Caddy settings
caddy_root: /usr/share/caddy
caddy_config_path: /etc/caddy
caddy_log_path: /var/log/caddy
caddy_user: caddy
caddy_group: caddy
caddy_download_custom_build: yes
caddy_systemd_protect_home: 'false'

# Firewall settings
firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443

firewall_firewalld_rules:
  - zone: public
    masquerade: yes

# Docker
docker_users:
  - "{{ ansibullbot_user }}"

authorized_keys:
  - user: centos
    comment: mkrizek@x240
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdIcSGGFCk4VLylSLCKHYoLK1vOEU9ebxJn5dtBY1MRAdEL7dDWzwfoovXzxkHWXOWYDWL2a\
      yZJHUmFfN9JVAg20FYNitU+PZlZs/H8xuWNjL4SbgOq6oBbZAHQnQ5EO0N2rfOMJXC5XEqAEDZVfOvJJt9qcPoBizMFIiTRT/yU47QFo7z3SGC\
      buMOEE9wZU+VFX8KKwHp1jP37dvLNBh/bdUwvo6RTpk7aUN8zv3BvAjUeT/hC6bbqMw4ibvWp/HbzKHFPBWp5mimIr/j2AbFLnY+c9T2/MJ1Fe\
      JIDeNC+uNR/J12XD2WQyUp4QowCsZMCKEkhNDVtm05yM5n+OV9"

  - user: centos
    comment: sdoran@aws_work
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfJ88NuTDKSpYq+wrDCd+AKg2l1jqg0qgXxjiNXwaEUOUllb5II0uin7xh/6jl9hLRbwVO\
      e/CjD+tjbb7IAuno6B/Nx4CqybArYv7w+GHH0fSrpLpojGzuO9IJ/p1Rxw7vum5INAQ9tPHScF2CwoANsYpmU1sgC+lzd3frobTOsQ9Gj/jE\
      h6I2Ugvm3N0Xjd4IA2788zsmOD/viHQt47AVOqFGhkyt/QlFdxw2MqUevkQiEmIv46aZkSLMtcsoLa/q63tCVaEl8vRRWhUVei8fvs5mVcPu\
      Jzq8jV92mtU+JUzh+SRpKynUsQKME4OB3OgUpTtpZvAJONWY4NS8P9t5"

  - user: "{{ ansibullbot_user }}"
    comment: mkrizek@x240
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdIcSGGFCk4VLylSLCKHYoLK1vOEU9ebxJn5dtBY1MRAdEL7dDWzwfoovXzxkHWXOWYDWL2a\
      yZJHUmFfN9JVAg20FYNitU+PZlZs/H8xuWNjL4SbgOq6oBbZAHQnQ5EO0N2rfOMJXC5XEqAEDZVfOvJJt9qcPoBizMFIiTRT/yU47QFo7z3SGC\
      buMOEE9wZU+VFX8KKwHp1jP37dvLNBh/bdUwvo6RTpk7aUN8zv3BvAjUeT/hC6bbqMw4ibvWp/HbzKHFPBWp5mimIr/j2AbFLnY+c9T2/MJ1Fe\
      JIDeNC+uNR/J12XD2WQyUp4QowCsZMCKEkhNDVtm05yM5n+OV9"

  - user: "{{ ansibullbot_user }}"
    comment: sdoran@aws_work
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfJ88NuTDKSpYq+wrDCd+AKg2l1jqg0qgXxjiNXwaEUOUllb5II0uin7xh/6jl9hLRbwVO\
      e/CjD+tjbb7IAuno6B/Nx4CqybArYv7w+GHH0fSrpLpojGzuO9IJ/p1Rxw7vum5INAQ9tPHScF2CwoANsYpmU1sgC+lzd3frobTOsQ9Gj/jE\
      h6I2Ugvm3N0Xjd4IA2788zsmOD/viHQt47AVOqFGhkyt/QlFdxw2MqUevkQiEmIv46aZkSLMtcsoLa/q63tCVaEl8vRRWhUVei8fvs5mVcPu\
      Jzq8jV92mtU+JUzh+SRpKynUsQKME4OB3OgUpTtpZvAJONWY4NS8P9t5"
