ansible_user: centos
ansibullbot_receiver_enabled: true

ansibullbot_github_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64336339633164353330346262343334326164346165313463653535333938626361366564326265
          6430333936663764663335616261373534343664306236360a633833373365306334376363303364
          61383631303035323862666365613639373139626665323131613937363765386534306363363038
          3466613564626639300a323465323739646538613965306564343835663230366339306138626239
          6565

ansibullbot_github_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37656238343239613334353762373333316466393034313839663665343463346634663230386231
          3561316238396561636334663561626633373938363034380a656434626662396366383732386237
          30313938663265326563393132623038306638636338313930363063353031353033383964393238
          6432363532623932620a623535313630646661646235313538333363366637383634333638373633
          30656336343231653861623462383864663464303636316665386566313532333830626131386230
          6661623263616435323435346164663265353037353066346334

ansibullbot_shippable_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31323936336635643537373832633937326138306334336461306634306565663561346262636461
          3636373539663831326338666331353831396562363334660a636530383433633736653434383137
          34323365363430613732383332373265653139643738336139323633646131623430623066663930
          6162363537616537300a643732353963363761393134646436336533313039663066323534646665
          36373662666662313034366562656463373431376562663935613563386437356131663138373261
          6161663961333533663062383066363130643161663237363165

ansibullbot_slack_url: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61346536653630656533633566373230316266313531343931313532313037656330656661386633
          3963323838303634383762326331306538363434326437350a623862653363346163613935656462
          30363438393263306366343538336635386661343764303362616430643736326439623533393961
          3062333061343434350a633662373861666638643037626230393933646637633436353231383838
          65373636373139656264343038383338643265326166613864633663613362303636613432643737
          37663061386162643964316436653437316435613534383132336530353830343532316333663566
          62396231623536633866613236386162383330356465383532323235306532336136633335363631
          65616564386466323139

# Caddy settings
ansibullbot_caddy_log_path: /var/log/caddy
caddy_config_path: /etc/caddy
caddy_user: caddy
caddy_group: caddy
caddy_root: /usr/share/caddy
caddy_default_port: 443
caddy_global_config_options:
  - order cgi last
caddy_plugins:
  - github.com/aksdb/caddy-cgi/v2

# Firewall settings
firewall_allowed_tcp_ports:
  - 22
  - 80
  - 443

firewall_firewalld_rules:
  - zone: public
    masquerade: yes

authorized_keys:
  - user: centos
    comment: mkrizek@x240
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdIcSGGFCk4VLylSLCKHYoLK1vOEU9ebxJn5dtBY1MRAdEL7dDWzwfoovXzxkHWXOWYDWL2a\
      yZJHUmFfN9JVAg20FYNitU+PZlZs/H8xuWNjL4SbgOq6oBbZAHQnQ5EO0N2rfOMJXC5XEqAEDZVfOvJJt9qcPoBizMFIiTRT/yU47QFo7z3SGC\
      buMOEE9wZU+VFX8KKwHp1jP37dvLNBh/bdUwvo6RTpk7aUN8zv3BvAjUeT/hC6bbqMw4ibvWp/HbzKHFPBWp5mimIr/j2AbFLnY+c9T2/MJ1Fe\
      JIDeNC+uNR/J12XD2WQyUp4QowCsZMCKEkhNDVtm05yM5n+OV9"

  - user: centos
    comment: sdoran@aws_work
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfJ88NuTDKSpYq+wrDCd+AKg2l1jqg0qgXxjiNXwaEUOUllb5II0uin7xh/6jl9hLRbwVO\
      e/CjD+tjbb7IAuno6B/Nx4CqybArYv7w+GHH0fSrpLpojGzuO9IJ/p1Rxw7vum5INAQ9tPHScF2CwoANsYpmU1sgC+lzd3frobTOsQ9Gj/jE\
      h6I2Ugvm3N0Xjd4IA2788zsmOD/viHQt47AVOqFGhkyt/QlFdxw2MqUevkQiEmIv46aZkSLMtcsoLa/q63tCVaEl8vRRWhUVei8fvs5mVcPu\
      Jzq8jV92mtU+JUzh+SRpKynUsQKME4OB3OgUpTtpZvAJONWY4NS8P9t5"

  - user: centos
    comment: tower2_deploy
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCk3j+kA6cfWin+Gq7RWZ1JQdpTbwEwpDPMN2GZy3uksDKnG8c+lXvfXhrtJ1XtQQmta06\
      J8oEp4pmf8QlFflftxoq/LRJ/YlmviSzvWbyqBYGtFo/Ndv0QU1UokY3jjLGiktvmmU7hH/xGDOBZLX9I2L/A0WiJ9HoAkKUGPfQwokTpbwP\
      lZ0U7zZ6ivqyRjnKmkzt6SkPExZ3JGIo5EfQoZMLRxyHmSvuTP+3dgNhTKGCbtQErPfU4tmL3u/1nz/7HoX1G0z8fee/QxgVCvWKmgbVXW28\
      Vsyio8ekFqVmViZae4m8SgE4viR10fj2Gultmp17bwnG8RWPqJ0liY+4hplEfZ+p4awcR3n1f4vyPW0somE5TTzU2v0ze+mhj0DusIyblfqs\
      BHOX55w2SVFW+rDB3rZ8MdN//JeYndFbLH69Sjggys+Yl9nUQ81sIo7LY4mdFzOOnn5wtBTzNf8NjwVn51jPh2XOg1AA2/QCnM7VweUfb3Aq\
      lrOCinTtySBz0eX75fbttyyGTYKGc4v8ZFDjFAxEl1ZxFmMP30LbCnAyc4Q2CQYp8BS1xxww9BXDQe+v91Z9NwYQNYTFDP0nMPh+yQOJdlSA\
      1ZBZIAtH/Z92Uz0CwgFZLeAaWXBxwKO3IezLGLTboojr9m1Fm3/sCPSSHK9SURB4iAopdOXNW7Q=="

  - user: "{{ ansibullbot_user }}"
    comment: mkrizek@x240
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdIcSGGFCk4VLylSLCKHYoLK1vOEU9ebxJn5dtBY1MRAdEL7dDWzwfoovXzxkHWXOWYDWL2a\
      yZJHUmFfN9JVAg20FYNitU+PZlZs/H8xuWNjL4SbgOq6oBbZAHQnQ5EO0N2rfOMJXC5XEqAEDZVfOvJJt9qcPoBizMFIiTRT/yU47QFo7z3SGC\
      buMOEE9wZU+VFX8KKwHp1jP37dvLNBh/bdUwvo6RTpk7aUN8zv3BvAjUeT/hC6bbqMw4ibvWp/HbzKHFPBWp5mimIr/j2AbFLnY+c9T2/MJ1Fe\
      JIDeNC+uNR/J12XD2WQyUp4QowCsZMCKEkhNDVtm05yM5n+OV9"

  - user: "{{ ansibullbot_user }}"
    comment: sdoran@aws_work
    key:
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfJ88NuTDKSpYq+wrDCd+AKg2l1jqg0qgXxjiNXwaEUOUllb5II0uin7xh/6jl9hLRbwVO\
      e/CjD+tjbb7IAuno6B/Nx4CqybArYv7w+GHH0fSrpLpojGzuO9IJ/p1Rxw7vum5INAQ9tPHScF2CwoANsYpmU1sgC+lzd3frobTOsQ9Gj/jE\
      h6I2Ugvm3N0Xjd4IA2788zsmOD/viHQt47AVOqFGhkyt/QlFdxw2MqUevkQiEmIv46aZkSLMtcsoLa/q63tCVaEl8vRRWhUVei8fvs5mVcPu\
      Jzq8jV92mtU+JUzh+SRpKynUsQKME4OB3OgUpTtpZvAJONWY4NS8P9t5"
