ansibullbot_sentry_server_name: ansibullbot
ansibullbot_fqdn: ansibullbot.eng.ansible.com
ansibullbot_ci_provider: azp
ansibullbot_azp:
  org: ansible
  project: 0bce9b4c-e7fb-4587-a45b-7d40c5f04699
  user: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39363938636134663933656164306261663630386439663239616439346365646562346430623538
    3733646161393636363730376636393337336132623636340a373839616462393664353137666238
    66656366616135356563346465383731353936653533343033346137326362663238333963626334
    3735353963393636610a613632613465313930356539303565316332363136383135373163393061
    64326435646432303466336532653039643938633964613636636662373837306336
  token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39633963316239663066353764373930653064653562383062323562373039323831613537663566
    6236343335373035386536336230326464333762343231340a353461393163303533656637306633
    39383833633361393537636236343462396633663562353639343633313763396463323038333235
    3930613138376164610a653439383533313162333634333863363539336639653338346661376464
    61386233613737353262623762646266336131383237613163336436643734613633663432333065
    61656565613262383261646535386666366137343664333938653862363061393238323233633736
    363662616133666562613030663866346639

ansibullbot_options:
  - daemonize
  - daemonize_interval={{ ansibullbot_daemonize_interval }}
  - debug
  - force
  - logfile {{ ansibullbot_log_path }}
  - resume
  - repo ansible/ansible
  - skip_no_update
  - verbose
