ansibullbot_sentry_server_name: ansibullbot
ansibullbot_fqdn: ansibullbot.eng.ansible.com
ansibullbot_ci_provider: azp
ansibullbot_azp:
  org: ansible
  project: fc938e26-c865-4d62-b731-a77bbe8bf5c4
  definition: 20
  user: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39363938636134663933656164306261663630386439663239616439346365646562346430623538
    3733646161393636363730376636393337336132623636340a373839616462393664353137666238
    66656366616135356563346465383731353936653533343033346137326362663238333963626334
    3735353963393636610a613632613465313930356539303565316332363136383135373163393061
    64326435646432303466336532653039643938633964613636636662373837306336
  token: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    39633963316239663066353764373930653064653562383062323562373039323831613537663566
    6236343335373035386536336230326464333762343231340a353461393163303533656637306633
    39383833633361393537636236343462396633663562353639343633313763396463323038333235
    3930613138376164610a653439383533313162333634333863363539336639653338346661376464
    61386233613737353262623762646266336131383237613163336436643734613633663432333065
    61656565613262383261646535386666366137343664333938653862363061393238323233633736
    363662616133666562613030663866346639

ansibullbot_options:
  - daemonize
  - daemonize_interval={{ ansibullbot_daemonize_interval }}
  - debug
  - force
  - logfile {{ ansibullbot_log_path }}
  - resume
  - repo ansible/ansible
  - skip_no_update
  - verbose

ansibullbot_slack_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30316336623938336266333130383338336633633963643035376266353537626462386631366563
  3664313665326361363062393831623630323635663931390a386335616464646262373136333033
  62346130353733323835353364356632653362386166303964366633633365396334653836306432
  3532333336353831650a666663353132376239323966303562646632643464313431393836646161
  62653634343664383532373735643962303666333530623065663230336538633637353563623135
  6237343134343037653738636134316239303163326532326135

ansibullbot_sentry_url: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63323033383535323038326635396566643832393334376239356435353766656531363765323164
  3431313663353637616332613361356534323866363165610a313465316435356465333830663637
  33343336366137666437613031393164336164303462373831383461313437353038626436366230
  3031623739666230380a323530363137333533663164303830373730373162613864656661343561
  39336661386633373538373633336262373939386165643162646137376532656233396433353434
  38336265326137343963363333323434353230626665666663346637333430333064333436343037
  373238326163396130616162616363643832
